[package]
name = "sherlock-currency"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
surf = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5"